name = "hue-far-apart"
compatibility_date = "2025-10-17"

routes = [
  { pattern = "hue-far-apart.website", custom_domain = true },
  { pattern = "*hue-far-apart.website/*", zone_name = "hue-far-apart.website" }
]

[assets]
directory = "./dist"

